### PR TITLE
Release 28-08-19

### PR DESCRIPTION
**Pull request by Clare72**
rename of flybase file and new odk release

### CODE REVIEW

**Comment by Clare72** [comment]
Not sure why this is failing on Travis - it says 'duplicate definition', but this is only supposed to be a warning, so what is the error?

**Comment by Clare72** [comment]
Oh, just spotted this at the top:
ERROR	missing_label	GO:0048018	rdfs:label

**Comment by Clare72** [comment]
this is 'receptor ligand activity' but I cant find the id or label in any of the files!

**Comment by dosumis** [comment]
I don't think the fail comes from this missing GO term label.  It looks like a robot fail on report generation:

2019-08-27 13:38:26,588 ERROR org.obolibrary.robot.ReportCommand - Report failed!
make: *** [fbcv.Makefile:236: obo_qc_fbcv.owl] Error 1

How urgent is this? May take some time to debug.  If we need to get a release out ASAP, we may be able to fix temporarily by commenting out report generation from the MakeFile.

**Comment by matentzn** [comment]
Yes, this is an irrelevant bug by the robot report generation process (which does not distinguish between native and foreign terms) that I am circumventing by injecting some assertions (in this case, bogus labels) into the artefact on which the QC is run.. I have fixed it now; if this happens again, and the error message at hand is unrelated to FBCV terms, you can try to inject an assertion [here](https://github.com/FlyBase/flybase-controlled-vocabulary/blob/master/src/ontology/components/qc_assertions.owl). Or ping me again and I will do it!

**Pull request merged**
